// Generated by scripts/export_ui_data.py on 2026-09-22 15:54 UTC - do not edit by hand.
// Regenerate with: python3 scripts/export_ui_data.py
// Numbers are real: prefixes from RIPEstat, IOC totals from the URLhaus /
// AbuseIPDB fetch, verdicts from triage_news.py.

export interface AsnEntry {
  code: string;
  country: string;
  asn: string;
  org: string;
  prefixCount: number;
}

export interface CountryEntry {
  code: string;
  country: string;
  asns: number;
  prefixes: number;
}

export interface Story {
  title: string;
  link: string;
  source: string;
  published: string;
  category: string;
  relevanceReason: string;
  whyItMatters: string;
  countries: string[];
  tags: string[];
}

export interface FilteredStory {
  title: string;
  source: string;
  reason: string;
}

export const lastRun = "2026-09-22 15:54 UTC";

export const numbers = {
  iocsChecked: 5400,
  sadcPrefixes: 2731,
  sadcAsns: 35,
  countriesTracked: 9,
  overlaps: 101,
  storiesKept: 18,
  storiesTriaged: 75,
  newsFeeds: 7,
};

export const countrySummary: CountryEntry[] = [
  {
    "code": "ZA",
    "country": "South Africa",
    "asns": 3,
    "prefixes": 1018
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asns": 14,
    "prefixes": 810
  },
  {
    "code": "TZ",
    "country": "Tanzania",
    "asns": 1,
    "prefixes": 254
  },
  {
    "code": "NA",
    "country": "Namibia",
    "asns": 3,
    "prefixes": 241
  },
  {
    "code": "MW",
    "country": "Malawi",
    "asns": 6,
    "prefixes": 190
  },
  {
    "code": "AO",
    "country": "Angola",
    "asns": 5,
    "prefixes": 78
  },
  {
    "code": "ZM",
    "country": "Zambia",
    "asns": 1,
    "prefixes": 71
  },
  {
    "code": "ZW",
    "country": "Zimbabwe",
    "asns": 1,
    "prefixes": 63
  },
  {
    "code": "BW",
    "country": "Botswana",
    "asns": 1,
    "prefixes": 6
  }
];

export const asnLedger: AsnEntry[] = [
  {
    "code": "AO",
    "country": "Angola",
    "asn": "AS36907",
    "org": "TV Cabo Angola",
    "prefixCount": 55
  },
  {
    "code": "AO",
    "country": "Angola",
    "asn": "AS37468",
    "org": "Angola Cables",
    "prefixCount": 16
  },
  {
    "code": "AO",
    "country": "Angola",
    "asn": "AS328718",
    "org": "AnyConnect Tecnologias e Telecomunicacoes",
    "prefixCount": 5
  },
  {
    "code": "AO",
    "country": "Angola",
    "asn": "AS37384",
    "org": "Banco Keve",
    "prefixCount": 1
  },
  {
    "code": "AO",
    "country": "Angola",
    "asn": "AS327691",
    "org": "Banco Millennium Atlantico",
    "prefixCount": 1
  },
  {
    "code": "BW",
    "country": "Botswana",
    "asn": "AS37678",
    "org": "Botswana Fibre Networks (BoFiNet)",
    "prefixCount": 6
  },
  {
    "code": "MW",
    "country": "Malawi",
    "asn": "AS37294",
    "org": "Telekom Networks Malawi (TNM)",
    "prefixCount": 149
  },
  {
    "code": "MW",
    "country": "Malawi",
    "asn": "AS36969",
    "org": "Malawi Telecommunications Limited",
    "prefixCount": 32
  },
  {
    "code": "MW",
    "country": "Malawi",
    "asn": "AS329220",
    "org": "Department of E-Government Malawi",
    "prefixCount": 6
  },
  {
    "code": "MW",
    "country": "Malawi",
    "asn": "AS328300",
    "org": "National Bank of Malawi",
    "prefixCount": 1
  },
  {
    "code": "MW",
    "country": "Malawi",
    "asn": "AS328844",
    "org": "Afrimax Malawi",
    "prefixCount": 1
  },
  {
    "code": "MW",
    "country": "Malawi",
    "asn": "AS36944",
    "org": "UbuntuNet Alliance (research & education)",
    "prefixCount": 1
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS37342",
    "org": "Movitel SA",
    "prefixCount": 541
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS37223",
    "org": "Vodacom Mocambique S.A",
    "prefixCount": 65
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS37110",
    "org": "Moztel Lda",
    "prefixCount": 48
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS25139",
    "org": "TVCABO - Comunicacoes Multimedia Lda",
    "prefixCount": 34
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS30619",
    "org": "TMCEL - Mocambique Telecom SA",
    "prefixCount": 33
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS36865",
    "org": "Teledata Mozambique",
    "prefixCount": 28
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS37697",
    "org": "Webmasters Lda",
    "prefixCount": 21
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS327700",
    "org": "MoRENet - Mozambique Research & Education Network",
    "prefixCount": 15
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS31960",
    "org": "Eduardo Mondlane University",
    "prefixCount": 9
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS36945",
    "org": "Mocambique Celular SARL",
    "prefixCount": 5
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS42235",
    "org": "Intra Data Communication",
    "prefixCount": 4
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS328274",
    "org": "BIM - Banco Internacional de Mocambique",
    "prefixCount": 3
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS328187",
    "org": "EDM - Electricidade de Mocambique",
    "prefixCount": 3
  },
  {
    "code": "MZ",
    "country": "Mozambique",
    "asn": "AS37477",
    "org": "Mozabanco",
    "prefixCount": 1
  },
  {
    "code": "NA",
    "country": "Namibia",
    "asn": "AS33763",
    "org": "Paratus Telecommunications",
    "prefixCount": 128
  },
  {
    "code": "NA",
    "country": "Namibia",
    "asn": "AS37009",
    "org": "MTC - Mobile Telecommunications Namibia",
    "prefixCount": 113
  },
  {
    "code": "NA",
    "country": "Namibia",
    "asn": "AS20459",
    "org": "Telecom Namibia",
    "prefixCount": 0
  },
  {
    "code": "TZ",
    "country": "Tanzania",
    "asn": "AS33765",
    "org": "Tanzania Telecommunications Co. (TTCL)",
    "prefixCount": 254
  },
  {
    "code": "ZA",
    "country": "South Africa",
    "asn": "AS37457",
    "org": "Telkom SA",
    "prefixCount": 507
  },
  {
    "code": "ZA",
    "country": "South Africa",
    "asn": "AS3741",
    "org": "Dimension Data (Internet Solutions)",
    "prefixCount": 505
  },
  {
    "code": "ZA",
    "country": "South Africa",
    "asn": "AS36943",
    "org": "1-Grid (PTY) Ltd",
    "prefixCount": 6
  },
  {
    "code": "ZM",
    "country": "Zambia",
    "asn": "AS37154",
    "org": "ZAMTEL - Zambia Telecommunications Company",
    "prefixCount": 71
  },
  {
    "code": "ZW",
    "country": "Zimbabwe",
    "asn": "AS37204",
    "org": "TelOne Zimbabwe",
    "prefixCount": 63
  }
];

export const stories: Story[] = [
  {
    "title": "WordPress Comment2Shell Flaw Can Turn Anonymous Comment XSS Into RCE via Admin Session",
    "link": "https://thehackernews.com/2026/09/wordpress-comment2shell-flaw-can-turn.html",
    "source": "The Hacker News",
    "published": "2026-09-22",
    "category": "vulnerability",
    "relevanceReason": "Affects wordpress \u2014 widely deployed in under-resourced organizations \u2014 via xss, rce.",
    "whyItMatters": "If you run wordpress, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "wordpress",
      "xss",
      "rce"
    ]
  },
  {
    "title": "Zyxel and Veeam Flaws Under Active Exploitation With Command and SYSTEM Access",
    "link": "https://thehackernews.com/2026/09/zyxel-and-veeam-flaws-under-active.html",
    "source": "The Hacker News",
    "published": "2026-09-22",
    "category": "vulnerability",
    "relevanceReason": "Affects zyxel, veeam \u2014 widely deployed in under-resourced organizations \u2014 via active exploitation, exploited.",
    "whyItMatters": "If you run zyxel, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "zyxel",
      "active-exploitation",
      "exploited"
    ]
  },
  {
    "title": "\u26a1 Weekly Recap: Cisco 0-Day, AI Agent RCE, ClickFix Attacks, ClickFix Surge, and Browser Hijacks",
    "link": "https://thehackernews.com/2026/09/weekly-recap-cisco-0-day-ai-agent-rce.html",
    "source": "The Hacker News",
    "published": "2026-09-21",
    "category": "vulnerability",
    "relevanceReason": "Affects cisco \u2014 widely deployed in under-resourced organizations \u2014 via rce, exposed.",
    "whyItMatters": "If you run cisco, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "cisco",
      "rce",
      "exposed"
    ]
  },
  {
    "title": "TASK#STOMP PowerShell Backdoor Steals Documents, Wi-Fi Passwords, and Clipboard Data",
    "link": "https://thehackernews.com/2026/09/taskstomp-powershell-backdoor-steals.html",
    "source": "The Hacker News",
    "published": "2026-09-21",
    "category": "other",
    "relevanceReason": "Affects powershell \u2014 widely deployed in under-resourced organizations \u2014 via backdoor.",
    "whyItMatters": "If you run powershell, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "powershell",
      "backdoor"
    ]
  },
  {
    "title": "SolarWinds Patches ARM Hard-Coded Key Flaw Enabling Unauthenticated RCE",
    "link": "https://thehackernews.com/2026/09/solarwinds-patches-arm-hard-coded-key.html",
    "source": "The Hacker News",
    "published": "2026-09-19",
    "category": "vulnerability",
    "relevanceReason": "Affects solarwinds \u2014 widely deployed in under-resourced organizations \u2014 via rce, remote code.",
    "whyItMatters": "If you run solarwinds, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "solarwinds",
      "rce",
      "remote-code"
    ]
  },
  {
    "title": "Critical Pre-Auth RCE in Orkes Conductor Workflow Platform Exploited in the Wild",
    "link": "https://thehackernews.com/2026/09/critical-pre-auth-rce-in-orkes.html",
    "source": "The Hacker News",
    "published": "2026-09-19",
    "category": "vulnerability",
    "relevanceReason": "Affects fortinet \u2014 widely deployed in under-resourced organizations \u2014 via rce, remote code.",
    "whyItMatters": "If you run fortinet, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "fortinet",
      "rce",
      "remote-code"
    ]
  },
  {
    "title": "BigCommerce alerts merchants of data breach linked to Ribon apps",
    "link": "https://www.bleepingcomputer.com/news/security/bigcommerce-alerts-merchants-of-data-breach-linked-to-ribon-apps/",
    "source": "BleepingComputer",
    "published": "2026-09-21",
    "category": "breach",
    "relevanceReason": "Affects bigcommerce \u2014 widely deployed in under-resourced organizations \u2014 via credential, data breach.",
    "whyItMatters": "If you run bigcommerce, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [
      "ML"
    ],
    "tags": [
      "bigcommerce",
      "credential",
      "data-breach"
    ]
  },
  {
    "title": "CISA alerts of active exploitation of three Linux kernel flaws",
    "link": "https://www.bleepingcomputer.com/news/security/cisa-alerts-of-active-exploitation-of-three-linux-kernel-flaws/",
    "source": "BleepingComputer",
    "published": "2026-09-21",
    "category": "vulnerability",
    "relevanceReason": "Affects linux \u2014 widely deployed in under-resourced organizations \u2014 via active exploitation, exploitation.",
    "whyItMatters": "If you run linux, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "linux",
      "active-exploitation",
      "exploitation"
    ]
  },
  {
    "title": "WordPress Click2Shell flaw lets hackers execute PHP on the server",
    "link": "https://www.bleepingcomputer.com/news/security/wordpress-click2shell-flaw-lets-hackers-execute-php-on-the-server/",
    "source": "BleepingComputer",
    "published": "2026-09-21",
    "category": "other",
    "relevanceReason": "Affects wordpress, php \u2014 widely deployed in under-resourced organizations \u2014 via cross-site.",
    "whyItMatters": "If you run wordpress, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "wordpress",
      "cross-site"
    ]
  },
  {
    "title": "Microsoft reminds admins to migrate Entra ID users to passkeys",
    "link": "https://www.bleepingcomputer.com/news/microsoft/microsoft-reminds-admins-to-migrate-entra-id-users-to-passkeys/",
    "source": "BleepingComputer",
    "published": "2026-09-21",
    "category": "phishing",
    "relevanceReason": "Affects entra \u2014 widely deployed in under-resourced organizations \u2014 via phishing.",
    "whyItMatters": "If you run entra, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "entra",
      "phishing"
    ]
  },
  {
    "title": "Malicious npm packages evade install-script defenses at runtime",
    "link": "https://www.bleepingcomputer.com/news/security/malicious-npm-packages-evade-install-script-defenses-at-runtime/",
    "source": "BleepingComputer",
    "published": "2026-09-20",
    "category": "policy_regulation",
    "relevanceReason": "Affects npm \u2014 widely deployed in under-resourced organizations \u2014 via malware, threat actors.",
    "whyItMatters": "If you run npm, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [
      "ML"
    ],
    "tags": [
      "npm",
      "malware",
      "threat-actors"
    ]
  },
  {
    "title": "RatHat Android Trojan Uses AI for Automation",
    "link": "https://www.securityweek.com/rathat-android-trojan-uses-ai-for-automation/",
    "source": "SecurityWeek",
    "published": "2026-09-21",
    "category": "other",
    "relevanceReason": "Affects android \u2014 widely deployed in under-resourced organizations \u2014 via malware.",
    "whyItMatters": "If you run android, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "android",
      "malware"
    ]
  },
  {
    "title": "Rust Team Members and Popular Crate Owners Targeted via Video Calls",
    "link": "https://www.securityweek.com/rust-team-members-and-popular-crate-owners-targeted-via-video-calls/",
    "source": "SecurityWeek",
    "published": "2026-09-21",
    "category": "other",
    "relevanceReason": "Affects rust \u2014 widely deployed in under-resourced organizations \u2014 via attackers.",
    "whyItMatters": "If you run rust, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "rust",
      "attackers"
    ]
  },
  {
    "title": "Organizations Warned of 3 Exploited Linux Kernel Vulnerabilities",
    "link": "https://www.securityweek.com/organizations-warned-of-3-exploited-linux-kernel-vulnerabilities/",
    "source": "SecurityWeek",
    "published": "2026-09-21",
    "category": "vulnerability",
    "relevanceReason": "Affects linux \u2014 widely deployed in under-resourced organizations \u2014 via exploited, attackers.",
    "whyItMatters": "If you run linux, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "linux",
      "exploited",
      "attackers"
    ]
  },
  {
    "title": "ShinyHunters cybercrime gang takes over Cl0p ransomware site, demands extortion payment",
    "link": "https://therecord.media/shinyhunters-clop-cyberattack-website",
    "source": "The Record",
    "published": "2026-09-21",
    "category": "ransomware",
    "relevanceReason": "Attack activity against payment-sector organizations, the same targets common across SADC.",
    "whyItMatters": "If you run affected software, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "ransomware"
    ]
  },
  {
    "title": "Attackers Abuse npm Trusted Publishing in GHAPPIER Campaign",
    "link": "https://www.infosecurity-magazine.com/news/attackers-abuse-npm-trusted/",
    "source": "Infosecurity Magazine",
    "published": "2026-09-21",
    "category": "other",
    "relevanceReason": "Affects npm \u2014 widely deployed in under-resourced organizations \u2014 via attackers.",
    "whyItMatters": "If you run npm, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "npm",
      "attackers"
    ]
  },
  {
    "title": "New Chinese-Made \u2018RatHat\u2019 Android Malware Leverages AI to Steal Financial Data",
    "link": "https://www.infosecurity-magazine.com/news/rathat-android-malware-ai-steal/",
    "source": "Infosecurity Magazine",
    "published": "2026-09-17",
    "category": "other",
    "relevanceReason": "Affects android \u2014 widely deployed in under-resourced organizations \u2014 via malware, backdoor.",
    "whyItMatters": "If you run android, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "android",
      "malware",
      "backdoor"
    ]
  },
  {
    "title": "Cisco Warns of Active Exploitation of Critical ISE Flaw",
    "link": "https://www.infosecurity-magazine.com/news/cisco-active-exploitation-critical/",
    "source": "Infosecurity Magazine",
    "published": "2026-09-17",
    "category": "vulnerability",
    "relevanceReason": "Affects cisco \u2014 widely deployed in under-resourced organizations \u2014 via active exploitation, exploitation.",
    "whyItMatters": "If you run cisco, verify you are on a patched version; unpatched instances are the most common entry point for small teams without dedicated security staff.",
    "countries": [],
    "tags": [
      "cisco",
      "active-exploitation",
      "exploitation"
    ]
  }
];

export const filteredOut: FilteredStory[] = [
  {
    "title": "One Hidden Meta Muse Setting Could Let Attackers Turn the AI Assistant Into a Backdoor",
    "source": "The Hacker News",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Fake LastPass Authenticator Installer Abuses Microsoft-Signed Driver to Kill Antivirus and EDR",
    "source": "The Hacker News",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Contagious Interview Campaign Compromises 30,000 Devices, Steals $10.71M in Crypto",
    "source": "The Hacker News",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Google Fined \u20ac403 Million Over GDPR Violations Tied to Location Data",
    "source": "The Hacker News",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "ClickFix Lures Deploy ChainScript RAT Using Polygon to Rotate C2 Infrastructure",
    "source": "The Hacker News",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Jade Sleet Linked to Indian IT Provider Breach With FLATROOF and ROOFDECK Backdoors",
    "source": "The Hacker News",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Claude Opus 5 Helped Researchers Take Over OpenAI Staff Accounts via Chained Flaws",
    "source": "The Hacker News",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Can You Prove a New CVE Is Exploitable Before Attackers Do? Learn How in This Webinar",
    "source": "The Hacker News",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Identity Visibility in 2026: The Foundation of Identity Security",
    "source": "The Hacker News",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Microsoft to retire Microsoft 365 Companion apps in December",
    "source": "BleepingComputer",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Google fined \u20ac403 million over location data privacy violations",
    "source": "BleepingComputer",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "Microsoft fixes broken Excel copy and paste for all Office users",
    "source": "BleepingComputer",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "FBI's CJIS v6.1: What Security Teams Need to Know.",
    "source": "BleepingComputer",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Microsoft: September updates break File History backup feature",
    "source": "BleepingComputer",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Researchers escape OpenAI Codex sandbox to run commands on host",
    "source": "BleepingComputer",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "BragJack attacks hijack AI browser agents through malicious extensions",
    "source": "BleepingComputer",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "North Korean WaterPlum hackers infected 30,000 devices worldwide",
    "source": "BleepingComputer",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "ShinyHunters hacks Clop leak site, threatens to extort ransomware gang",
    "source": "BleepingComputer",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Viral AI actress' hotline face-scans every caller, watches their mood",
    "source": "BleepingComputer",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "US Proposes AI Incident Alert System in Talks With China, Bessent Says",
    "source": "SecurityWeek",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Google Hit With $463 Million Fine for EU Location Data Rule Breach",
    "source": "SecurityWeek",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Fake LastPass Installers Push Kernel-Level EDR Killer, \u2018Rapuncel\u2019 Stealer",
    "source": "SecurityWeek",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "CISO Conversations: Noopur Davis \u2013 The Accidental Global CISO at Comcast",
    "source": "SecurityWeek",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Dragos Completes NetRise and runZero Acquisitions Following Accenture Deal",
    "source": "SecurityWeek",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "CrowdSec Confirms Source Code Stolen in Supply Chain Attack",
    "source": "SecurityWeek",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Colorado Water Utilities Hit by Cyberattacks Targeting OT Systems",
    "source": "SecurityWeek",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "EU data regulator fines Google more than $460 million for location data violations",
    "source": "The Record",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "Belgian table tennis, gymnastics federations hit by cyberattacks",
    "source": "The Record",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Cyberattack hits University of Munich, potentially exposing student financial data",
    "source": "The Record",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "LinkedIn wins court order blocking mass scraping of user data",
    "source": "The Record",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Huntress expands cybersecurity platform to Africa through QBS Software partnership - MSSP Alert",
    "source": "Google News: Africa cybersecurity",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "Terra Industries leads strategic investment in Nigerian cybersecurity startup Aeon - Portal ERP",
    "source": "Google News: Africa cybersecurity",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "Zuo Bruno Builds Zuoix Into a Preventive Cybersecurity Firm Across Africa - We are Tech",
    "source": "Google News: Africa cybersecurity",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "Terra Industries puts $1M into Aeon, a Nigerian cybersecurity startup - Resilience Media",
    "source": "Google News: Africa cybersecurity",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "Africa\u2019s AI Governance, Data & Cybersecurity to Take Center Stage at 4th TICON Confab in Zambia - CediRates",
    "source": "Google News: Africa cybersecurity",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "Burkina Faso\u2019s Great\u00a0Green\u00a0Wall\u00a0is being stalled by more than war",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "5 questions to understand Somaliland President Irro\u2019s Washington debut",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "US plays catch-up with China in race for Nigeria\u2019s critical minerals",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "US-Africa Week Ahead: Washington retreats from African priorities at the UN",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Tinubu\u2019s poll rebound reveals Nigeria\u2019s town-country divide",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "How al-Amoudi broke Morocco\u2019s only refinery",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Meet UN Secretary-General Guterres\u2019 Africa team",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Algeria accuses UAE of trying to sway two presidential elections",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Mali: Kyiv\u2019s support for Sahel insurgents clashes with US goals",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "After Niger\u2019s coup attempt, Tiani is running out of people to trust",
    "source": "The Africa Report",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Google Hit with \u20ac403m GDPR Fine Over Location Data Practices",
    "source": "Infosecurity Magazine",
    "reason": "Industry, business, or political news with no vulnerability, incident, or technique defenders can act on."
  },
  {
    "title": "New Exvicy ClickFix Framework Built on Rival ErrTraffic's Code",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "ShinyHunters Claim Hack of Rival Ransomware Gang Clop",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Experts Alarmed Over Gyazo\u2019s Breach of 490 Million Metadata Records",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Revolut Customers Targeted with New Wave of Phishing Attacks",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "New Settra Ransomware Variant Deployed in Attacks on Retail and Manufacturing",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "CISA Upgrades Vulnerability Reporting Platform with More Automation",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Manufacturing Accounts for 22% of all Ransomware Victims",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "FamousSparrow Swaps SparrowDoor For New SparroWocky Backdoor",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "CISA Urges Critical Infrastructure to Plant Decoys Inside Networks",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "Cyber Essentials Has Record Year but Takeup Remains Low",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  },
  {
    "title": "AI Agent Carries Out Multi-Stage Data Theft Attack",
    "source": "Infosecurity Magazine",
    "reason": "No African angle, and no widely-deployed-platform issue with a transferable lesson for low-resource defenders."
  }
];

export const categoryLabels: Record<string, string> = {
  vulnerability: 'Vulnerability',
  breach: 'Breach',
  ransomware: 'Ransomware',
  phishing: 'Phishing',
  policy_regulation: 'Policy',
  infrastructure: 'Infrastructure',
  tooling: 'Tooling',
  other: 'Note',
};
