#!/usr/bin/env python3
"""Export pipeline data as the typed module the React UI consumes.

Reads data/prefixes.json, data/iocs.json, data/matches.json,
data/triaged_news.json and writes ui/src/data/feedData.ts.

Run after the fetch/triage steps (locally or in CI) before `npm run build`.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "ui" / "src" / "data" / "feedData.ts"


def ts(s) -> str:
    return json.dumps(s if s else "")


def main():
    prefixes = json.loads((DATA / "prefixes.json").read_text()) if (DATA / "prefixes.json").exists() else []
    iocs = json.loads((DATA / "iocs.json").read_text()) if (DATA / "iocs.json").exists() else []
    matches = json.loads((DATA / "matches.json").read_text()) if (DATA / "matches.json").exists() else []
    triaged = json.loads((DATA / "triaged_news.json").read_text()) if (DATA / "triaged_news.json").exists() else []

    relevant = [t for t in triaged if t["triage"]["relevant"]]
    total = len(triaged)

    # Ledger: one row per ASN, sorted by country then prefix count.
    ledger = [
        {
            "code": p["code"],
            "country": p["country"],
            "asn": p["asn"],
            "org": p["name"],
            "prefixCount": len(p["prefixes"]),
        }
        for p in prefixes
    ]
    ledger.sort(key=lambda a: (a["code"], -a["prefixCount"]))

    countries = []
    for code in sorted({a["code"] for a in ledger}):
        rows = [a for a in ledger if a["code"] == code]
        countries.append({
            "code": code,
            "country": rows[0]["country"],
            "asns": len(rows),
            "prefixes": sum(r["prefixCount"] for r in rows),
        })
    countries.sort(key=lambda c: -c["prefixes"])

    stories = []
    for t in relevant:
        tr = t["triage"]
        stories.append({
            "title": t.get("title", ""),
            "link": t.get("link", ""),
            "source": t.get("source", ""),
            "published": t.get("date", ""),
            "category": tr.get("category", "other"),
            "relevanceReason": tr.get("relevance_reason", ""),
            "whyItMatters": tr.get("why_it_matters_africa", ""),
            "countries": tr.get("countries", []),
            "tags": tr.get("suggested_tags", []),
        })

    filtered = []
    for t in triaged:
        if t["triage"]["relevant"]:
            continue
        filtered.append({
            "title": t.get("title", ""),
            "source": t.get("source", ""),
            "reason": t["triage"].get("relevance_reason", ""),
        })

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    n_countries = len(countries)

    out = f"""// Generated by scripts/export_ui_data.py on {now} - do not edit by hand.
// Regenerate with: python3 scripts/export_ui_data.py
// Numbers are real: prefixes from RIPEstat, IOC totals from the URLhaus /
// AbuseIPDB fetch, verdicts from triage_news.py.

export interface AsnEntry {{
  code: string;
  country: string;
  asn: string;
  org: string;
  prefixCount: number;
}}

export interface CountryEntry {{
  code: string;
  country: string;
  asns: number;
  prefixes: number;
}}

export interface Story {{
  title: string;
  link: string;
  source: string;
  published: string;
  category: string;
  relevanceReason: string;
  whyItMatters: string;
  countries: string[];
  tags: string[];
}}

export interface FilteredStory {{
  title: string;
  source: string;
  reason: string;
}}

export const lastRun = {ts(now)};

export const numbers = {{
  iocsChecked: {len(iocs)},
  sadcPrefixes: {sum(a['prefixCount'] for a in ledger)},
  sadcAsns: {len(ledger)},
  countriesTracked: {n_countries},
  overlaps: {len(matches)},
  storiesKept: {len(relevant)},
  storiesTriaged: {total},
  newsFeeds: 7,
}};

export const countrySummary: CountryEntry[] = {json.dumps(countries, indent=2)};

export const asnLedger: AsnEntry[] = {json.dumps(ledger, indent=2)};

export const stories: Story[] = {json.dumps(stories, indent=2)};

export const filteredOut: FilteredStory[] = {json.dumps(filtered, indent=2)};

export const categoryLabels: Record<string, string> = {{
  vulnerability: 'Vulnerability',
  breach: 'Breach',
  ransomware: 'Ransomware',
  phishing: 'Phishing',
  policy_regulation: 'Policy',
  infrastructure: 'Infrastructure',
  tooling: 'Tooling',
  other: 'Note',
}};
"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(out)
    print(f"Wrote {OUT}: {len(ledger)} ASNs / {n_countries} countries, "
          f"{len(relevant)} stories, {len(filtered)} filtered")


if __name__ == "__main__":
    main()
